require('./menu.test');
require('./timetable.test');
require('./table.test');
require('./restaurant.test');
require('./repositoryManager.test');
require('./restaurantManager.test');
require('./query.test');
require('./api.test');
require('./denormalizers');
