#%RAML 1.0
---
title: Restaurant Catalog API
version: v1
baseUri: api.restaurant_catalog.com/{version}
schemas: 
    Table:
        properties:
            tableId: string
            people: integer
    Dish:
        properties:
            name: string
            img: string
            price: number
            description: string
            ingredients: string[]
            #dish_type: string ->da definire la collection (vegetariano, ecc...)
    MenuSection:
        properties:
            sortIndex: integer
            name: string
            dishes: Dish[]
    Menu:
        properties:
            restId: string
            menuSections: MenuSection[]
    OpeningInterval:
        properties:
            opening:
                properties:
                    h: integer
                    m: integer
            closing:
                properties:
                    h: integer
                    m: integer
    DayTimetable:
        properties:
            dayIndex: integer
            openingIntevals: OpeningInterval[]
    Timetable:
        type: DayTimetable[]
        maxItems: 7
    Review:
        properties:
            score: integer
            reviewCount: integer
    Restaurant:
        properties:
            restId: string
            restaurantName: string
            review: Review
            menu: Menu
            timetable: Timetable
            tables: Table[]
            mainImg: string
            images: string[]
            telephone:
                type: string
                pattern: ^\+[0-9]?()[0-9](\s|\S)(\d[0-9]{9})$
            # location: x, y
            # recensioni: da definire

/restaurant:
    get:
        description: Get a restaurant information by giving the restaurant id
        headers: 
        queryParameters:
            restId: 
                description: Specify the restaurant id of the restaurant required
                required: true
                type: string
                example: 0553dec2-8e58-4639-ae0c-620e9022b3c6
        responses: 
            200:
                body:
                    application/json:
                        type: Restaurant
                        message: String
            400:
                body:
                    application/json:
                        message: String
    post:
        description: Creates a new restaurant
        headers: 
        body: 
            application/json:
                properties:
                    restaurant: Restaurant
        responses: 
            200:
                body:
                    application/json:
                     message: String
            400:
                body:
                    application/json:
                     message: String
    /dish:
        post:
            description: Add a new dish to an MenuSection
            headers: 
            body: 
                application/json:
                    properties:
                        restId:String
                        menuSectionName: String
                        dish: Dish
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
        delete:
            description: Remove a dish from MenuSection
            headers: 
            body: 
                application/json:
                    properties:
                        restId:String
                        menuSectionName: String
                        dish: string
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String

    /menusection:
        post:
            description: Add a new menu section
            headers: 
            body: 
                application/json:
                    properties:
                        restId:String
                        menuSections: MenuSection
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
        delete:
            description: Remove a menu section
            headers: 
            body: 
                application/json:
                    properties:
                        restId:String
                        menuSections: string
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String

    /images:
        post:
            description: Add new Images to Restaurant
            headers: 
            body: 
                application/json:
                    properties:
                        restId: String
                        images: String[]
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
        delete:
            description: Remove  Images from Restaurant
            headers: 
            body: 
                application/json:
                    properties:
                        restId: String
                        images: String[]
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
    /table:
        post:
            description: Add new table to Restaurant
            headers: 
            body: 
                application/json:
                    properties:
                        restId: String
                        table: Table
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
        delete:
            description: Remove table from Restaurant
            headers: 
            body: 
                application/json:
                    properties:
                        restId: String
                        tableId: String
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
    /timetable:
        post:
            description: Set open-time Restaurant
            headers: 
            body: 
                application/json:
                    properties:
                        restId: String
                        timetable: Timetable
            responses: 
                200:
                    body:
                        application/json:
                        message: String
                400:
                    body:
                        application/json:
                        message: String
    
