#%RAML 1.0
---
title: Restaurant Catalog API
version: v1
baseUri: api.restaurant_catalog.com/{version}
schemas: 
    Error:
        properties:
            error: string
    UUID:
        type: string
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$
    Table:
        properties:
            tableId: string
            people: integer
    Price:
        properties:
            value: number
            currency: string
    Dish:
        properties:
            name: string
            image: string
            price: Price
            description: string
            ingredients: string[]
            #dish_type: string ->da definire la collection (vegetariano, ecc...)
    MenuSection:
        properties:
            sortIndex: integer
            name: string
            dishes: Dish[]
    Menu:
        type: MenuSection[]
    OpeningInterval:
        properties:
            opening:
                properties:
                    h: integer
                    m: integer
            closing:
                properties:
                    h: integer
                    m: integer
    DayTimetable:
        properties:
            dayOfWeek: integer
            openings: OpeningInterval[]
    Timetable:
        type: DayTimetable[]
        maxItems: 7
    Coordinates:
        properties:
            lat: number
            lon: number
    Location:
        properties:
            address: string
            coordinates: Coordinates
    Review:
        properties:
            score: integer
            reviewCount: integer
    Restaurant:
        properties:
            restId: UUID
            restaurantName: string
            review: Review
            menu: Menu
            timetable: Timetable
            tables: Table[]
            mainImg: string
            images: string[]
            telephone:
                type: string
                pattern: ^\+[0-9]?()[0-9](\s|\S)(\d[0-9]{9})$
            location: Location
            # recensioni: da definire

/restaurants:
    post:
        description: Creates a new restaurant
        headers: 
        body: 
            application/json:
                properties:
                    restaurant: Restaurant
        responses: 
            200:
                body:
                    application/json:
            400:
                body:
                    application/json:
                        type: Error
    get:
        description: Gets nearby restaurants
        headers:
        queryParameters:
            coordinates:
                description: Coordinates near to which search
                type: Coordinates
            address:
                description: Address near to which search
                type: string
            offset:
                description: Offset used for pagination (optional)
                type: number
            radius:
                description: Radius used for the search of the query
                type: number
        responses:
            200:
                body:
                    application/json:
                        properties:
                            restaurants:
                                description: The list of restaurants
                                type: Restaurant[]
                            hits:
                                description: The total number of restaurants found
                                type: number
                            radius:
                                description: Radius used for the query in meters
                                type: number
            400:
                body:
                    application/json:
                        type: Error

    /{restId}: 
        get:
            description: Get a restaurant information by giving the restaurant id
            headers:
            responses: 
                200:
                    body:
                        application/json:
                            type: Restaurant
                400:
                    body:
                        application/json:
                            type: Error
        /menu:
            get:
                description: Get the restaurant menu
                headers:
                responses: 
                200:
                    body:
                        application/json:
                            type: Menu
                400:
                    body:
                        application/json:
                            type: Error
            /menuSections:
                post:
                    description: Add a new menu section
                    headers: 
                    body: 
                        application/json:
                            properties:
                                restId: UUID
                                menuSections: MenuSection
                    responses: 
                        200:
                            body:
                                application/json:
                        400:
                            body:
                                application/json:
                                    type: Error
                
                /{sectionName}:
                    delete:
                    description: Remove the menu section
                    headers: 
                    responses: 
                        200:
                            body:
                                application/json:
                        400:
                            body:
                                application/json:
                                    type: Error
                        404:
                            body:
                                application/json:
                                    type: Error
                    /dishes: 
                        post:
                            description: Add a new dish to a MenuSection
                            headers: 
                            body: 
                                application/json:
                                    properties:
                                        restId: UUID
                                        menuSectionName: string
                                        dish: Dish
                            responses: 
                                200:
                                    body:
                                        application/json:
                                400:
                                    body:
                                        application/json:
                                            type: Error
                        /{dishName}: 
                            put:
                                description: Update a dish
                                headers:
                                body:
                                    application/json:
                                        type: Dish

                            delete:
                                description: Remove a dish from MenuSection
                                headers: 
                                body: 
                                    application/json:
                                        properties:
                                            restId: UUID
                                            menuSectionName: string
                                            dish: string
                                responses: 
                                    200:
                                        body:
                                            application/json:
                                    400:
                                        body:
                                            application/json:
                                                type: Error


        /images:
            post:
                description: Add new Images to Restaurant
                headers: 
                body: 
                    application/json:
                        properties:
                            restId: UUID
                            images: string[]
                responses: 
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
                                type: Error
            delete:
                description: Remove the provided images from Restaurant
                headers: 
                body: 
                    application/json:
                        properties:
                            restId: UUID
                            images: string[]
                responses: 
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
                                type: Error
        /tables:
            put:
                description: Replace the whole collection of tables of the restaurant
                headers:
                body:
                    application/json:
                        type: Table[]
                responses:
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
            post:
                description: Add new table to Restaurant
                headers: 
                body: 
                    application/json:
                        properties:
                            restId: UUID
                            table: Table
                responses: 
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
                                type: Error
            /{tableId}:
                delete:
                    description: Remove table from Restaurant
                    headers: 
                    body: 
                        application/json:
                            properties:
                                restId: UUID
                                tableId: string
                    responses: 
                        200:
                            body:
                                application/json:
                        400:
                            body:
                                application/json:
                                    type: Error
        /timetable:
            post:
                description: Set open-time Restaurant
                headers: 
                body: 
                    application/json:
                        properties:
                            restId: UUID
                            timetable: Timetable
                responses: 
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
                                type: Error
        /location:
            post:
                description: Set restaurant's location
                headers: 
                body: 
                    application/json:
                        type: Location
                responses: 
                    200:
                        body:
                            application/json:
                    400:
                        body:
                            application/json:
                                type: Error
    
